qt5.inc: package metatypes files
* enabled since qtbase commit:
  commit c5e9d7e504172707f7705d03ae27006c45eb5eac
  Author: Ulf Hermann <ulf.hermann@qt.io>
  Date:   Wed Aug 28 16:09:25 2019 +0200

    Generate metatypes.json for QtCore, QtGui, and QtWidgets

    These libraries contain types which are exposed to QML from
    qtdeclarative.

    Change-Id: Ie0edaef94fcb40074b6f6b2ea1a1c3a77ed3e9a9
    Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>

* fixes:
  ERROR: qtbase-5.14.99+gitAUTOINC+2e7a28958d-r0 do_package: QA Issue: qtbase: Files/directories were installed but not shipped in any package:
  /usr/lib/metatypes
  /usr/lib/metatypes/qt5gui_metatypes.json
  /usr/lib/metatypes/qt5core_metatypes.json
  /usr/lib/metatypes/qt5widgets_metatypes.json
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  qtbase: 4 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>